name: Test and Build
on:
  push:
    branches-ignore: main
jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install --force
      - name: Run Tests
        env:
          CI: true
#         run: npm test
      - name: Build
        run: npm run build
